language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.6
  - nightly

notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Packing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Packing")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
