language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("Packing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());  Codecov.submit(process_folder())'
